"""Lock-In week simulator.

Handoff sec.11, and the reason this whole project exists. In Lock-In mode only
ONE game per player counts each week, so the classic fantasy currency - points
per game multiplied by games played - is simply the wrong unit of account.

Two consequences drive everything downstream:

1.  **Games per week is leverage, not volume.** A player with four games in a
    week gets four draws from their scoring distribution and keeps the best one
    they choose to lock. A two-game player gets two. The marginal value of the
    3rd and 4th game is large even though only one game can ever count.

2.  **Right-tail shape beats the mean.** Between two players averaging 35 FP, the
    volatile one is worth materially more, because the week keeps the good draw
    and discards the bad ones. This inverts the usual "consistency is king"
    intuition of season-long fantasy.

VERIFIED MECHANIC (see docs/lock_in_mechanics.md): if a manager never locks a
game, Sleeper automatically takes the player's FINAL game of the week. The
do-nothing baseline is therefore ``last_game``, not ``max`` and not the mean.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping, Sequence

import numpy as np

from src.lockin.strategies import (
    OptimalIIDStrategy,
    PercentileStrategy,
    PlayerContext,
    Strategy,
    ThresholdStrategy,
    build_strategies,
    continuation_values,
)

# Strategies that are computed structurally rather than by consulting a decider.
PERFECT = "perfect"
LAST_GAME = "last_game"


@dataclass(frozen=True)
class WeekResult:
    """Outcome of one simulated fantasy week."""

    scores: tuple[float, ...]
    locked_value: float
    locked_index: int
    strategy: str

    @property
    def regret(self) -> float:
        """How much the decision left on the table versus perfect foresight."""
        return max(self.scores) - self.locked_value if self.scores else 0.0


@dataclass(frozen=True)
class LockInProfile:
    """A player's Lock-In valuation across every strategy.

    ``lock_in_advantage`` is the headline number the handoff asks for: how much
    more a manager banks per week than the player's raw scoring average, purely
    because Lock-In lets them keep their best draw.
    """

    player_id: str
    games_per_week: float
    strategy_values: Mapping[str, float]
    primary_strategy: str
    mean_fp: float

    @property
    def lockin_value(self) -> float:
        return self.strategy_values[self.primary_strategy]

    @property
    def perfect_value(self) -> float:
        return self.strategy_values.get(PERFECT, self.lockin_value)

    @property
    def auto_value(self) -> float:
        return self.strategy_values.get(LAST_GAME, self.mean_fp)

    @property
    def lock_in_advantage(self) -> float:
        """Weekly FP gained over a naive per-game average."""
        return self.lockin_value - self.mean_fp

    @property
    def decision_value(self) -> float:
        """Weekly FP gained by paying attention rather than letting it auto-lock."""
        return self.lockin_value - self.auto_value

    @property
    def clairvoyance_gap(self) -> float:
        """Weekly FP left on the table versus an oracle. Pure upper-bound slack."""
        return self.perfect_value - self.lockin_value


def simulate_week(
    scores: Sequence[float],
    strategy: Strategy,
    ctx: PlayerContext,
    auto_lock_fallback: str = "last_game",
) -> WeekResult:
    """Walk one week's games in order, applying the strategy's lock decision.

    The strategy sees each score exactly once, in chronological order, and knows
    only how many games remain - never what those games will produce.
    """
    values = [float(s) for s in scores]
    if not values:
        return WeekResult((), 0.0, -1, getattr(strategy, "name", "unknown"))

    last = len(values) - 1
    for index, score in enumerate(values):
        remaining = last - index
        if remaining == 0:
            break
        if strategy.decide(score, remaining, ctx):
            return WeekResult(tuple(values), score, index, getattr(strategy, "name", "unknown"))

    # Never locked - the league's auto-lock rule decides.
    fallback_index = _fallback_index(values, auto_lock_fallback)
    return WeekResult(
        tuple(values), values[fallback_index], fallback_index, getattr(strategy, "name", "unknown")
    )


def _fallback_index(values: Sequence[float], rule: str) -> int:
    if rule == "first_game":
        return 0
    if rule == "best_game":
        return int(np.argmax(values))
    return len(values) - 1  # last_game (Sleeper's actual behaviour)


class LockInSimulator:
    """Monte-Carlo Lock-In valuation for a player.

    Weeks are generated by resampling the player's own game-level FP distribution,
    which preserves the empirical skew and fat right tail that make Lock-In value
    diverge from mean FP.
    """

    def __init__(
        self,
        model_cfg: Mapping,
        league_cfg: Mapping | None = None,
        rng: np.random.Generator | None = None,
    ):
        self.model_cfg = dict(model_cfg)
        self.lockin_cfg = self.model_cfg.get("lockin", {})
        self.strategies = build_strategies(self.model_cfg)
        self.primary = self.lockin_cfg.get("primary_strategy", "optimal_iid")
        self.report = list(self.lockin_cfg.get("report_strategies", [PERFECT, LAST_GAME, self.primary]))
        self.auto_lock = (league_cfg or {}).get("auto_lock_fallback", "last_game")
        self.rng = rng or np.random.default_rng(20262027)

    # -- exact, distribution-based valuation --------------------------------
    def expected_weekly_value(self, distribution: np.ndarray, games: int, strategy_name: str) -> float:
        """Expected weekly Lock-In score for a fixed number of games.

        ``perfect`` and ``last_game`` are computed in closed form from the
        empirical distribution rather than simulated, because exact answers are
        available and cheaper:

            perfect    = E[max of `games` i.i.d. draws], via the empirical CDF
            last_game  = E[F]  (the final game is just one unconditioned draw)
        """
        sample = np.asarray(distribution, dtype=float)
        if sample.size == 0 or games <= 0:
            return 0.0
        if games == 1:
            return float(np.mean(sample))

        if strategy_name == PERFECT:
            ordered = np.sort(sample)
            n = ordered.size
            # P(max <= x_(i)) = (i/n)^games -> weight of the i-th order statistic.
            upper = (np.arange(1, n + 1) / n) ** games
            lower = (np.arange(0, n) / n) ** games
            return float(np.sum(ordered * (upper - lower)))

        if strategy_name == LAST_GAME:
            return float(np.mean(sample))

        return self._simulate_expected(sample, games, strategy_name)

    def _simulate_expected(self, sample: np.ndarray, games: int, strategy_name: str, n_weeks: int = 4000) -> float:
        """Vectorised expected weekly value under a lock-threshold strategy.

        Every realistic strategy here reduces to the same rule: *lock the first
        game at or above a threshold that depends only on how many games remain*.
        That makes the whole Monte Carlo expressible as one comparison against a
        broadcast threshold vector, rather than a Python loop over weeks - which
        matters, because a real player pool runs this tens of thousands of times.

        ``simulate_week`` remains the reference implementation, and
        ``test_vectorised_lockin_matches_scalar`` pins the two together.
        """
        thresholds = self._threshold_vector(sample, games, strategy_name)
        if thresholds is None:
            # Strategy is not threshold-shaped; fall back to the explicit loop.
            return self._simulate_expected_loop(sample, games, strategy_name, n_weeks)

        draws = self.rng.choice(sample, size=(n_weeks, games), replace=True)
        if games == 1:
            return float(draws[:, 0].mean())

        # Decisions are only made on games 0..games-2; the last game is forced.
        decisions = draws[:, : games - 1] >= thresholds[np.newaxis, :]
        locked_any = decisions.any(axis=1)
        first_lock = np.argmax(decisions, axis=1)

        chosen = draws[np.arange(n_weeks), first_lock]
        fallback = self._fallback_values(draws)
        return float(np.where(locked_any, chosen, fallback).mean())

    def _threshold_vector(self, sample: np.ndarray, games: int, strategy_name: str) -> np.ndarray | None:
        """Lock threshold for each decision game, or None if not threshold-shaped."""
        if games <= 1:
            return np.array([])
        strategy = self.strategies.get(strategy_name)
        if strategy is None:
            return None

        if isinstance(strategy, ThresholdStrategy):
            return np.full(games - 1, float(strategy.threshold))
        if isinstance(strategy, PercentileStrategy):
            return np.full(games - 1, float(np.percentile(sample, strategy.percentile)))
        if isinstance(strategy, OptimalIIDStrategy):
            values = continuation_values(sample, max_games=max(8, games))
            # At decision index i there are (games-1-i) games still to come.
            remaining = np.arange(games - 1, 0, -1)
            return values[np.clip(remaining, 0, len(values) - 1)]
        return None

    def _fallback_values(self, draws: np.ndarray) -> np.ndarray:
        """Value taken when the strategy never locks, per the league's auto-lock rule."""
        if self.auto_lock == "first_game":
            return draws[:, 0]
        if self.auto_lock == "best_game":
            return draws.max(axis=1)
        return draws[:, -1]

    def _simulate_expected_loop(self, sample: np.ndarray, games: int, strategy_name: str, n_weeks: int) -> float:
        """Reference implementation: explicit week-by-week simulation."""
        strategy = self.strategies[strategy_name]
        ctx = PlayerContext(
            distribution=sample,
            continuation_values=continuation_values(sample, max_games=max(8, games)),
        )
        draws = self.rng.choice(sample, size=(n_weeks, games), replace=True)
        total = 0.0
        for week in draws:
            total += simulate_week(week, strategy, ctx, self.auto_lock).locked_value
        return total / n_weeks

    # -- full-season profile -------------------------------------------------
    def profile(
        self,
        player_id: str,
        distribution: np.ndarray,
        games_per_week_pmf: Mapping[int, float],
    ) -> LockInProfile:
        """Value a player across the real distribution of weekly game counts.

        ``games_per_week_pmf`` maps games-in-a-week -> probability, and is where
        the schedule enters the valuation. A player on a team with many 4-game
        weeks is worth strictly more in Lock-In than an identical player on a
        2-game-heavy schedule, and this is the term that captures it.
        """
        sample = np.asarray(distribution, dtype=float)
        mean_fp = float(np.mean(sample)) if sample.size else 0.0

        total_probability = sum(games_per_week_pmf.values()) or 1.0
        pmf = {int(k): float(v) / total_probability for k, v in games_per_week_pmf.items()}

        values: dict[str, float] = {}
        for name in self.report:
            expected = 0.0
            for games, probability in pmf.items():
                if probability <= 0:
                    continue
                expected += probability * self.expected_weekly_value(sample, games, name)
            values[name] = expected

        if self.primary not in values:
            values[self.primary] = sum(
                p * self.expected_weekly_value(sample, g, self.primary) for g, p in pmf.items()
            )

        return LockInProfile(
            player_id=player_id,
            games_per_week=sum(g * p for g, p in pmf.items()),
            strategy_values=values,
            primary_strategy=self.primary,
            mean_fp=mean_fp,
        )


def reconstruct_weeks(
    game_dates: Sequence, scores: Sequence[float], week_start_weekday: int = 1
) -> list[list[float]]:
    """Group a player's real game log into fantasy weeks.

    Handoff sec.11: "Given historical weekly schedules, reconstruct each player's
    games within a fantasy week." Weeks run Monday-Sunday by default, matching
    Sleeper's NBA calendar.
    """
    import pandas as pd

    if len(game_dates) == 0:
        return []
    frame = pd.DataFrame({"date": pd.to_datetime(list(game_dates)), "fp": list(scores)})
    frame = frame.sort_values("date")
    # pandas dayofweek is Monday=0; ISO weekday is Monday=1.
    offset = (frame["date"].dt.dayofweek + 1 - week_start_weekday) % 7
    frame["week_start"] = frame["date"] - pd.to_timedelta(offset, unit="D")
    return [group["fp"].tolist() for _, group in frame.groupby("week_start", sort=True)]
